### PR TITLE
CT: Add create init code limit

### LINKED ISSUE #489: Limit init code size
Starting with Shanghai a CREATE/CREATE2 call fails if the initcode size is greater than the chain's maximum initcode size.

### PR DESCRIPTION
**Pull request by simonlechner**
Starting with Shanghai, the init code of a create call can no longer have arbitrary size. These changes are added to the create/create2 effect implementation.

Fixes #489, can only be merged after #498 and #499 to ensure correct CT execution.

### CODE REVIEW

**Review by facuMH — DISMISSED** [review]

**Review by HerbertJordan — APPROVED** [review]

**Review by LuisPH3 — CHANGES_REQUESTED** [review]
please rebase with main and remove revision guards in the Create instructions

**Review by HerbertJordan — APPROVED** [review]

File: go/ct/spc/specification.go [hunk 1]
```diff
@@ -1557,7 +1554,6 @@ func getAllRules() []Rule {
 		pushes:    1,
 		conditions: []Condition{
 			Eq(ReadOnly(), false),
-			RevisionBounds(MinRevision, R11_Paris),
```
Comment (facuMH) [inline go/ct/spc/specification.go:1560]: why remove them instead of making them `AnyKnownRevision()` ?

**Review by facuMH — APPROVED** [review]

File: go/ct/spc/specification.go (hunk 1 above)
Comment (simonlechner) [reply go/ct/spc/specification.go:1560]: This constrained is already added by the `rulesFor` function.

**Review by LuisPH3 — APPROVED** [review]
