### PR TITLE
Floria: Implement gas refunding

### LINKED ISSUE #575: Floria: Add gas refund after fail call

### PR DESCRIPTION
**Pull request by simonlechner**
This PR implements gas refunding in Floria. Further, the gas integration tests are split into multiple functions and an end to end test for gas billing/handling using a mock interpreter is introduced. 

Fixes #575 and #603.

### CODE REVIEW

File: go/integration_test/processor/gas_billing_test.go [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+			},
+			result: tosca.Result{
+				GasLeft:   5000,
+				Success:   true,
+				GasRefund: 300,
+			},
+		},
+		"failed": {
+			after: WorldState{
+				{1}: Account{Balance: tosca.NewValue(522500), Nonce: 5},
```
Comment (HerbertJordan) [inline go/integration_test/processor/gas_billing_test.go:55]: The only difference between the two after states in these tests seems to be the balance of account 1. It should reduce the code complexity a lot if you only put the balance in the test case specification and build the rest in the test run function below.

File: go/integration_test/processor/gas_billing_test.go [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+			},
+			receipt: tosca.Receipt{
+				Success: true,
+				GasUsed: 95200,
+			},
+			result: tosca.Result{
+				GasLeft:   5000,
+				Success:   true,
+				GasRefund: 300,
+			},
```
Comment (HerbertJordan) [inline go/integration_test/processor/gas_billing_test.go:51]: nit: I think definitions are in general easier to read if they are causally ordered; Input parameters should be followed by output vlaues.

In this test case, the `result` leads to the `after` state and `receipt`. So I would argue that `result` should be defined first, followed by `after` and `receipt`. Also, `result` as a name for an input parameter makes reading this code hard.

File: go/integration_test/processor/gas_billing_test.go [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+
+func TestProcessor_GasBillingEndToEnd(t *testing.T) {
+	tests := map[string]struct {
+		after   WorldState
+		receipt tosca.Receipt
+		result  tosca.Result
+	}{
+		"success": {
+			after: WorldState{
+				{1}: Account{Balance: tosca.NewValue(524000), Nonce: 5},
```
Comment (HerbertJordan) [inline go/integration_test/processor/gas_billing_test.go:34]: I am having a hard time understanding where this final balance is coming from ... so it is difficult to understand the specification covered by this test.

File: go/integration_test/processor/processor_gas_test.go [hunk 4]
```diff
@@ -145,132 +143,225 @@ func getGasTestScenarios() map[string]Scenario {
...
+		"GasPriceCalculation": {
+			Before: WorldState{
+				{1}: Account{Balance: tosca.NewValue(floria.TxGas * gasPrice), Nonce: 4},
+				{2}: Account{},
+			},
+			Transaction: tosca.Transaction{
+				Sender:    tosca.Address{1},
+				Recipient: &tosca.Address{2},
+				GasLimit:  floria.TxGas,
+				GasPrice:  tosca.ValueFromUint256(uint256.NewInt(gasPrice)),
```
Comment (HerbertJordan) [inline go/integration_test/processor/processor_gas_test.go:293]: Here and at other places:
```suggestion
				GasPrice:  tosca.NewValue(gasPrice),
```

File: go/integration_test/processor/processor_gas_test.go [hunk 5]
```diff
@@ -145,132 +143,225 @@ func getGasTestScenarios() map[string]Scenario {
...
-			Sender:    tosca.Address{},
-			Recipient: &tosca.Address{2},
-			GasLimit:  floria.TxGas + 100,
-			Nonce:     4,
+	return testCases
+}
+
+func gasPricingTestCases() map[string]Scenario {
+	gasPrice := uint64(10)
+	testCases := map[string]Scenario{
```
Comment (HerbertJordan) [inline go/integration_test/processor/processor_gas_test.go:283]: I would try to minimize the details that need to be specified in those cases. Everything that is the same in all of those should be handled in the Run function below.

Here, it looks like all you need is the before and after value for the account's balance and the receipt.

File: go/integration_test/processor/processor_gas_test.go [hunk 6]
```diff
@@ -145,132 +143,225 @@ func getGasTestScenarios() map[string]Scenario {
...
+			},
+			Receipt: tosca.Receipt{
+				Success: true,
+				GasUsed: floria.TxGas,
+			},
 		},
-		After: WorldState{
-			{}:  Account{Balance: tosca.NewValue(100), Nonce: 5},
-			{2}: Account{Balance: tosca.NewValue(0)},
+		"GasPriceCalculationExcessGas": {
```
Comment (HerbertJordan) [inline go/integration_test/processor/processor_gas_test.go:306]: This label is wrong. It is not "excess gas" but "excess balance".

**Review by HerbertJordan — CHANGES_REQUESTED** [review]

**Review by HerbertJordan — COMMENTED** [review]
You should try to minimize test cases to make them more readable and verifiable.

File: go/integration_test/processor/gas_billing_test.go (hunk 3 above)
Comment (simonlechner) [reply go/integration_test/processor/gas_billing_test.go]: I don't think it makes sense to write down the whole gas computation in the unit tests, the idea of this end to end test is to make sure both the reference implementation as well as floria deliver the same results. I added a comment.

File: go/integration_test/processor/processor_gas_test.go (hunk 5 above)
Comment (simonlechner) [reply go/integration_test/processor/processor_gas_test.go]: I was able to reduce the unit test length and also restructured parts of the other gas specific tests.

File: go/integration_test/processor/gas_billing_test.go (hunk 3 above)
Comment (HerbertJordan) [reply go/integration_test/processor/gas_billing_test.go]: Something to consider though: unlike in the interpreter case, the reference version of the processor may be buggy.

File: go/processor/floria/processor_test.go [hunk 7]
```diff
@@ -116,41 +115,138 @@ func TestProcessor_BuyGasInsufficientBalance(t *testing.T) {
...
+				Sender:   tosca.Address{},
+				GasLimit: 1000,
+			},
+			result: tosca.CallResult{
+				GasLeft:   500,
+				Success:   false,
+				GasRefund: 500,
+			},
+			revision:        tosca.R10_London,
+			expectedGasLeft: 500,
```
Comment (HerbertJordan) [inline go/processor/floria/processor_test.go:213]: In case of an unsuccessful execution all gas should be consumed .. so this value should be `0`, right?

The implementation of `calculateGasLeft` seems to assume that in case of a unsuccessful execution `result.GasLeft` is `0`. This is probably the case for all interpreter implementations, and so the implementation will likely produce the correct result. If so, this test case describes an impossible input.

**Review by HerbertJordan — APPROVED** [review]

File: go/processor/floria/processor_test.go (hunk 7 above)
Comment (simonlechner) [reply go/processor/floria/processor_test.go]: Right, I mainly wanted to test that the refund is not added back in an unsuccessful case. I changed the gasLeft to 0 to avoid any confusion.

**Review by HerbertJordan — APPROVED** [review]

**Review by HerbertJordan — APPROVED** [review]
Thanks for documenting the expectations using code!
